sudo: required 
services:
 - docker
matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_install: 
      - docker build -t bucketlist .
      - docker run -d -p 9090:9090 bucketlist
      - docker ps -a

    - language: node_js
      node_js: 8
 
